{{- if .Values.secrets.newrelicLicenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license
  labels:
    {{- include "browser-hitl.labels" . | nindent 4 }}
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: {{ .Values.secrets.newrelicLicenseKey | b64enc | quote }}
{{- end }}
